import { DeleteOutlined, EditOutlined, EnvironmentOutlined, PlusOutlined, ShoppingOutlined } from '@ant-design/icons'
import { Button, Drawer, Empty, Form, Input, Spin, Tag, message } from 'antd'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import client from '../api/client'
import type { CustomerPrivacyState, Order } from '../types/shop'

type Address = { id: number; recipient_name: string; phone: string; province: string; city: string; district: string; detail: string; is_default: boolean }
type AddressInput = Omit<Address, 'id'>
const labels: Record<string, string> = { category: '品类', brand: '品牌', size: '尺寸', budget: '预算', purchase_frequency: '购买频率', recent_products: '最近购买商品' }
const logistics: Record<string, [string, string]> = { CREATED: ['订单已创建', '等待完成支付'], PAID_SIMULATED: ['已支付，等待出库', '订单正在安排发货'], COMPLETED: ['交易完成', '订单已完成，可在订单详情申请售后'] }

export default function Account() {
  const [orders, setOrders] = useState<Order[]>([]); const [addresses, setAddresses] = useState<Address[]>([]); const [preferences, setPreferences] = useState<CustomerPrivacyState>(); const [loading, setLoading] = useState(true)
  const [drawerOpen, setDrawerOpen] = useState(false); const [editing, setEditing] = useState<Address>(); const [saving, setSaving] = useState(false); const [form] = Form.useForm<AddressInput>()
  const load = async () => { setLoading(true); try { const [orderResponse, addressResponse, preferenceResponse] = await Promise.all([client.get<Order[]>('/shop/orders'), client.get<Address[]>('/shop/addresses'), client.get<CustomerPrivacyState>('/customer-assistant/privacy')]); setOrders(orderResponse.data); setAddresses(addressResponse.data); setPreferences(preferenceResponse.data) } catch { message.error('个人信息暂时无法加载，请稍后重试') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const openForm = (address?: Address) => { setEditing(address); form.setFieldsValue(address ?? { recipient_name: '', phone: '', province: '', city: '', district: '', detail: '', is_default: addresses.length === 0 }); setDrawerOpen(true) }
  const save = async (values: AddressInput) => { setSaving(true); try { if (editing) await client.put(`/shop/addresses/${editing.id}`, values); else await client.post('/shop/addresses', values); message.success(editing ? '收货地址已更新' : '收货地址已添加'); setDrawerOpen(false); await load() } catch { message.error('收货地址保存失败') } finally { setSaving(false) } }
  const setDefault = async (address: Address) => { try { await client.put(`/shop/addresses/${address.id}`, { ...address, is_default: true }); await load() } catch { message.error('默认地址设置失败') } }
  const remove = async (address: Address) => { try { await client.delete(`/shop/addresses/${address.id}`); await load() } catch { message.error('收货地址删除失败') } }
  if (loading) return <main className="page-wrap account-page" aria-live="polite"><Spin /></main>
  return <main className="page-wrap account-page" aria-labelledby="account-title">
    <header className="account-page__header"><div><p className="shop-eyebrow">ACCOUNT CENTER</p><h1 id="account-title">我的</h1><p>集中查看订单进度、收货信息与购物偏好。</p></div><div className="account-page__header-actions"><Link to="/shop/orders"><Button>全部订单</Button></Link></div></header>
    <section className="account-section account-section--orders" data-testid="account-section-orders" aria-labelledby="account-orders-title"><div className="account-section__heading"><div><h2 id="account-orders-title">订单与配送</h2><p>配送状态基于当前订单状态展示，不包含物流单号或虚构轨迹。</p></div><Link to="/shop/orders">查看全部</Link></div>{orders.length ? <div className="account-orders">{orders.slice(0, 3).map((order) => { const status = logistics[order.status] || [order.status, '订单状态更新中']; return <article className="account-order" key={order.id}><div className="account-order__top"><Link to={`/shop/orders/${order.id}`}>{order.order_no}</Link><Tag color="blue">{status[0]}</Tag></div><p>{order.items.map((item) => `${String(item.product_snapshot_json.name || item.product_snapshot_json.model || '商品信息待同步')} x ${item.quantity}`).join('；') || '暂无商品信息'}</p><div className="account-order__footer"><span>{status[1]}</span><strong>¥{order.total_amount.toFixed(2)}</strong></div></article> })}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无订单"><Link to="/shop"><Button type="primary" icon={<ShoppingOutlined />}>去逛商城</Button></Link></Empty>}</section>
    <section className="account-section account-section--addresses" data-testid="account-section-addresses" aria-labelledby="account-addresses-title"><div className="account-section__heading"><div><h2 id="account-addresses-title">收货地址</h2><p>下单时可选择默认地址，也可在此统一维护。</p></div><Button type="primary" icon={<PlusOutlined />} aria-label="新增地址" onClick={() => openForm()}>新增地址</Button></div>{addresses.length ? <div className="account-addresses">{addresses.map((address) => <article className="account-address" key={address.id}><div><strong>{address.recipient_name} {address.phone}</strong>{address.is_default && <Tag color="blue">默认</Tag>}<p><EnvironmentOutlined /> {address.province}{address.city}{address.district}{address.detail}</p></div><div className="account-address__actions">{!address.is_default && <Button type="link" onClick={() => void setDefault(address)}>设为默认</Button>}<Button type="text" icon={<EditOutlined />} aria-label={`编辑${address.recipient_name}的地址`} onClick={() => openForm(address)} /><Button type="text" danger icon={<DeleteOutlined />} aria-label={`删除${address.recipient_name}的地址`} onClick={() => void remove(address)} /></div></article>)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无收货地址"><Button onClick={() => openForm()}>添加收货地址</Button></Empty>}</section>
    <section className="account-section account-section--preferences" data-testid="account-section-preferences" aria-labelledby="account-preferences-title"><div className="account-section__heading"><div><h2 id="account-preferences-title">购物偏好</h2><p>系统使用以下标签整理购物偏好；具体值仅在您授权后生成和展示。</p></div><Link to="/shop/privacy"><Button>偏好设置</Button></Link></div><div className="account-preferences" aria-label="系统定义的购物偏好标签">{Object.entries(labels).map(([key, label]) => { const preference = preferences?.preferences.find((item) => item.key === key); return <div className="account-preference" key={key}><span>{label}</span>{preferences?.enabled && preference ? <strong>{JSON.stringify(preference.value)}</strong> : <em>{preferences?.enabled ? '尚无记录' : '未授权生成'}</em>}</div> })}</div></section>
    <Drawer title={editing ? '编辑收货地址' : '新增收货地址'} open={drawerOpen} onClose={() => setDrawerOpen(false)} destroyOnClose><Form form={form} layout="vertical" onFinish={save}><Form.Item label="收件人" name="recipient_name" rules={[{ required: true, message: '请输入收件人' }]}><Input /></Form.Item><Form.Item label="手机号" name="phone" rules={[{ required: true, message: '请输入手机号' }, { pattern: /^1\d{10}$/, message: '请输入 11 位手机号' }]}><Input inputMode="numeric" /></Form.Item><div className="address-form__region"><Form.Item label="省" name="province" rules={[{ required: true, message: '请输入省' }]}><Input /></Form.Item><Form.Item label="市" name="city" rules={[{ required: true, message: '请输入市' }]}><Input /></Form.Item><Form.Item label="区" name="district" rules={[{ required: true, message: '请输入区' }]}><Input /></Form.Item></div><Form.Item label="详细地址" name="detail" rules={[{ required: true, message: '请输入详细地址' }]}><Input.TextArea rows={3} /></Form.Item><Form.Item name="is_default" hidden><Input /></Form.Item><Button htmlType="submit" type="primary" block loading={saving}>保存地址</Button></Form></Drawer>
  </main>
}
